TRAIN:
  ENABLE: True
  DATASET: audioset
  BATCH_SIZE: 64
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  INPUT_CHANNEL_NUM: [1]
  MULTI_LABEL: True
AUDIO_DATA:
  SAMPLING_RATE: 16000
  CLIP_SECS: 5.0
  NUM_FRAMES: 500
  WINDOW_LENGTH: 20
  HOP_LENGTH: 10
ENCODER:
  RETURN_EMBD: False
  DROPPATH_RATE: 0.1
  DEPTH: 10
  DIM_MUL: [[1, 2.0], [3, 2.0], [8, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [8, 2.0]]
  POOL_KVQ_KERNEL: [3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [4, 4]
  POOL_Q_STRIDE: [[0, 1, 1], [1, 2, 2], [2, 1, 1], [3, 2, 2], [4, 1, 1], [5, 1, 1], [6, 1, 1], [7, 1, 1], [8, 2, 2], [9, 1, 1]]
  REL_POS_SPATIAL: False
BN:
  USE_PRECISE_STATS: True
  FREEZE: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  LR_POLICY: cosine
  BASE_LR: 0.05
  STEPS: [0, 30, 40]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 2.5
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
MIXUP:
  ENABLE: True
MODEL:
  MODEL_NAME: "MViTv2-T"
  NUM_CLASSES: 527
  LOSS_FUNC: "bce_logit"
  PLAYBACK: 0
  FREEZE_ENCODER: False
  IGNORE_DECODER: True
TEST:
  ENABLE: False
  DATASET: audioset
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 2
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
  TRAIN_CROP_SIZE: (400, 128)
  TEST_CROP_SIZE: (400, 128)
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
AUDIOSET:
  SET: 'balanced'
