TRAIN:
  ENABLE: True
  DATASET: audioset
  BATCH_SIZE: 64
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  INPUT_CHANNEL_NUM: [1]
  MULTI_LABEL: True
AUDIO_DATA:
  SAMPLING_RATE: 16000
  CLIP_SECS: 10.0
  NUM_FRAMES: 1000
  WINDOW_LENGTH: 20
  HOP_LENGTH: 25
ENCODER:
  DROPPATH_RATE: 0.3
  DEPTH: 24
  DIM_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  HEAD_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  POOL_KVQ_KERNEL: [3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [4, 4]
  POOL_Q_STRIDE: [[0, 1, 1], [1, 1, 1], [2, 2, 2], [3, 1, 1], [4, 1, 1], [5, 2, 2], [6, 1, 1], [7, 1, 1], [8, 1, 1], [9, 1, 1], [10, 1, 1], [11, 1, 1], [12, 1, 1], [13, 1, 1], [14, 1, 1], [15, 1, 1], [16, 1, 1], [17, 1, 1], [18, 1, 1], [19, 1, 1], [20, 1, 1], [21, 2, 2], [22, 1, 1], [23, 1, 1]]
  REL_POS_SPATIAL: False
DECODER:
  INPUT_CHANNELS: 768
  DEPTH: 4
  FUSION_LOC: 'features'
SOLVER:
  LR_POLICY: cosine
  BASE_LR: 5e-3
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 2.5
  WARMUP_START_LR: 5e-5
  OPTIMIZING_METHOD: sgd
MIXUP:
  ENABLE: False
MODEL:
  MODEL_NAME: "PlayItBackX3"
  NUM_CLASSES: 527
  LOSS_FUNC: "bce_logit"
  PLAYBACK: 3
  FREEZE_ENCODER: True
TEST:
  ENABLE: False
  DATASET: audioset
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 2
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
  TRAIN_CROP_SIZE: (400, 128)
  TEST_CROP_SIZE: (400, 128)
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
