TRAIN:
  ENABLE: True
  DATASET: vggsound
  BATCH_SIZE: 64
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  INPUT_CHANNEL_NUM: [1]
AUDIO_DATA:
  SAMPLING_RATE: 16000
  CLIP_SECS: 5.0
  NUM_FRAMES: 500
  WINDOW_LENGTH: 20
  HOP_LENGTH: 10
MVIT:
  DROPPATH_RATE: 0.3
  DEPTH: 24
  DIM_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  HEAD_MUL: [[2, 2.0], [5, 2.0], [21, 2.0]]
  POOL_KVQ_KERNEL: [3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [4, 4]
  POOL_Q_STRIDE: [[0, 1, 1], [1, 1, 1], [2, 2, 2], [3, 1, 1], [4, 1, 1], [5, 2, 2], [6, 1, 1], [7, 1, 1], [8, 1, 1], [9, 1, 1], [10, 1, 1], [11, 1, 1], [12, 1, 1], [13, 1, 1], [14, 1, 1], [15, 1, 1], [16, 1, 1], [17, 1, 1], [18, 1, 1], [19, 1, 1], [20, 1, 1], [21, 2, 2], [22, 1, 1], [23, 1, 1]]
  REL_POS_SPATIAL: False
BN:
  USE_PRECISE_STATS: True
  FREEZE: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  #BASE_LR_SCALE_NUM_SHARDS: True
  #BASE_LR: 0.00025
  #STEP_SIZE: 1
  #LR_POLICY: cosine
  #MAX_EPOCH: 50
  #WARMUP_EPOCHS: 12.
  #WEIGHT_DECAY: 0.05
  #OPTIMIZING_METHOD: adamw
  #CLIP_GRAD_L2NORM: 1.0
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 30, 40]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 1.0
  WARMUP_START_LR: 0.001
  OPTIMIZING_METHOD: sgd
MODEL:
  MODEL_NAME: "MViTv2-T"
  NUM_CLASSES: 309
  LOSS_FUNC: "cross_entropy"
TEST:
  ENABLE: False
  DATASET: vggsound
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 2
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
  TRAIN_CROP_SIZE: (400, 128)
  TEST_CROP_SIZE: (400, 128)
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
