TRAIN:
  ENABLE: True
  DATASET: vggsound
  BATCH_SIZE: 64
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  INPUT_CHANNEL_NUM: [1]
AUDIO_DATA:
  SAMPLING_RATE: 16000
  CLIP_SECS: 5.0
  NUM_FRAMES: 500
  WINDOW_LENGTH: 20
  HOP_LENGTH: 10
ENCODER:
  DROPPATH_RATE: 0.1
  DEPTH: 10
  DIM_MUL: [[1, 2.0], [3, 2.0], [8, 2.0]]
  HEAD_MUL: [[1, 2.0], [3, 2.0], [8, 2.0]]
  POOL_KVQ_KERNEL: [3, 3]
  POOL_KV_STRIDE_ADAPTIVE: [4, 4]
  POOL_Q_STRIDE: [[0, 1, 1], [1, 2, 2], [2, 1, 1], [3, 2, 2], [4, 1, 1], [5, 1, 1], [6, 1, 1], [7, 1, 1], [8, 2, 2], [9, 1, 1]]
  REL_POS_SPATIAL: False
DECODER:
  INPUT_CHANNELS: 768
  DEPTH: 2
  FUSION_LOC: 'features'
SOLVER:
  LR_POLICY: cosine
  BASE_LR: 5e-4
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: 2.5
  WARMUP_START_LR: 5e-5
  OPTIMIZING_METHOD: sgd
MIXUP:
  ENABLE: True
MODEL:
  MODEL_NAME: "PlayItBackX2"
  NUM_CLASSES: 309
  LOSS_FUNC: "cross_entropy"
  PLAYBACK: 1
  FREEZE_ENCODER: True
TEST:
  ENABLE: False
  DATASET: vggsound
  BATCH_SIZE: 64
  NUM_ENSEMBLE_VIEWS: 2
DATA_LOADER:
  NUM_WORKERS: 16
  PIN_MEMORY: True
  TRAIN_CROP_SIZE: (400, 128)
  TEST_CROP_SIZE: (400, 128)
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
