TRAIN:
  ENABLE: True
  DATASET: vggsound
  BATCH_SIZE: 32
  EVAL_PERIOD: 2
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
DATA:
  INPUT_CHANNEL_NUM: [1]
AUDIO_DATA:
  SAMPLING_RATE: 16000
  CLIP_SECS: 5.119
  NUM_FRAMES: 128
  WINDOW_LENGTH: 20
  HOP_LENGTH: 40
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 101
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [23], [3]]
BN:
  USE_PRECISE_STATS: True
  FREEZE: False
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.01
  LR_POLICY: steps_with_relative_lrs
  STEPS: [0, 30, 40]
  LRS: [1, 0.1, 0.01]
  MAX_EPOCH: 50
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-4
  WARMUP_EPOCHS: -1.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: [309,]
  ARCH: slow
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: False
  DATASET: vggsound
  BATCH_SIZE: 32
  NUM_ENSEMBLE_VIEWS: 2
DATA_LOADER:
  NUM_WORKERS: 8
  PIN_MEMORY: True
NUM_GPUS: 8
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .
